version: '3'

services:

  web_server:
    image: golang:1.12
    volumes:
      - ./app:/go/src/github.com/mjmcconnell/go_playground
    ports:
      - 8080:8080
    working_dir: /go/src/github.com/mjmcconnell/go_playground
